### ISSUE TITLE
Sine marketplace dissapeared

### ISSUE THREAD

**Issue by thegoldknight** [CosmoCreeper/Sine#220]
<img width="332" height="407" alt="Image" src="https://github.com/user-attachments/assets/b2e62440-d08a-4b44-a03e-eeac28bc46c0" />
I've tried reinstalling Sine using latest release and clearing startup cache.

**Comment by CosmoCreeper** [comment]
@thegoldknight Reinstall via the auto-installer. There was a minor issue regarding v2.1.2.

EDIT: Sorry, did not see you tried reinstalling.

Press Ctrl+Shift+J, what logs are there?

**Comment by thegoldknight** [comment]
<img width="1438" height="875" alt="Image" src="https://github.com/user-attachments/assets/eb05423d-5ec8-45a9-86e5-bcb6ce0b271a" />

I'm on mac btw

**Comment by CosmoCreeper** [comment]
@thegoldknight Search for sine and look for errors. Is there anything?

**Comment by thegoldknight** [comment]
<img width="1440" height="875" alt="Image" src="https://github.com/user-attachments/assets/639e6aa2-1c60-4f29-a995-18abaacbf1dc" />
no errors

**Comment by AmazingVanish** [comment]
I am installing for the first time. Tried both Beta and Twilight. Getting the following:

<img width="1088" height="641" alt="Image" src="https://github.com/user-attachments/assets/3035f405-c703-4807-b060-e80399727673" />

No Cosine Mods marketplace in Settings

**Comment by CosmoCreeper** [comment]
@AmazingVanish @thegoldknight 

Go to the settings page and press Ctrl+Shift+I, what logs are there?

**Comment by AmazingVanish** [comment]
@CosmoCreeper Interesting. I switched to the General tab. Closed Twilight and reopened it and now it's there

**Comment by CosmoCreeper** [comment]
@AmazingVanish hmm, sometimes a second restart is all thats needed.

**Comment by neohdx** [comment]
> [@CosmoCreeper](https://github.com/CosmoCreeper) Interesting. I switched to the General tab. Closed Twilight and reopened it and now it's there

same

**Comment by thegoldknight** [comment]
> [@AmazingVanish](https://github.com/AmazingVanish) [@thegoldknight](https://github.com/thegoldknight)
> 
> Go to the settings page and press Ctrl+Shift+I, what logs are there?

I'm using mac so I'm assuming you mean Web Developer Tools?
<img width="1275" height="794" alt="Image" src="https://github.com/user-attachments/assets/8984df98-251a-472c-9671-fa518be4399f" />

<img width="1280" height="760" alt="Image" src="https://github.com/user-attachments/assets/0616dccd-7ddf-45a7-9d86-ce7f786359d6" />

**Comment by CosmoCreeper** [comment]
@thegoldknight oh, and then click console.

**Comment by thegoldknight** [comment]
> [@thegoldknight](https://github.com/thegoldknight) oh, and then click console.

nothing in console

**Comment by CosmoCreeper** [comment]
@thegoldknight There has been an update. Could you try deleting the JS folder from your chrome folder and then reinstalling via the auto-installer now?

**Comment by drahmedshaheen** [comment]
@CosmoCreeper yes removing sin using cli tool or manually due to access denied and reinstall it make it works. Thank you so much!

**Comment by mlelien** [comment]
I'm having the same issue. Where do I find the JS and chrome folder so I can delete it?

<img width="2118" height="1664" alt="Image" src="https://github.com/user-attachments/assets/85f83e51-a021-46e4-9376-1f8614fe5067" />

**Comment by mehmetcb02** [comment]
On Linux I always get this error on console whenever I try to install any mods:
> Uncaught (in promise) DOMException: Could not write to `/home/mehmetcb/.zen/h4f5088f.Default (release)/chrome/JS/Nebula_Nebula.uc.js': failed to open file for writing (NS_ERROR_FILE_ACCESS_DENIED)

Also tried this but no luck :
> try deleting the JS folder from your chrome folder and then reinstalling via the auto-installer now?

Btw I can't run the installer without sudo on my user account. If I do it throws:

> Failed to install config.js: Failed to download https://raw.githubusercontent.com/MrOtherGuy/fx-autoconfig/master/program/config.js: Access to the path '/opt/zen-browser-bin/config.js' is denied.

**Comment by CosmoCreeper** [comment]
@mehmetcanbursalioglu you need to change the permissions ti your chrome folder to all users, not just the root user.

**Comment by CosmoCreeper** [comment]
@mlelien your chrome folder is in your profile folder which you can find in about:support, scroll to profile folder, and click open folder next to it.

**Comment by mehmetcb02** [comment]
> [@mehmetcanbursalioglu](https://github.com/mehmetcanbursalioglu) you need to change the permissions ti your chrome folder to all users, not just the root user.

Yeah that was it. I fixed the permissions and it works great now. Thanks

**Comment by Exclesa** [comment]
I'm having the same issue, although a few days ago I got it working again by installing the newer version. This time however, re-installing it as the newest version did nothing. Sine disappeared and won't show up. Here is the logs

<img width="1400" height="1086" alt="Image" src="https://github.com/user-attachments/assets/c3f81ffc-640c-460c-ab13-bd13ec48df78" />

**Comment by LimoSenpai** [comment]
I have the same issue, the only error I get on the settings page is the following:
` DOMException: DOM mutated from promiseDocumentFlushed callbacks `

If I try to uninstall sine with the installer I get the following error:
`Failed to uninstall Sine: Could not find a part of the path '/home/user/.zen/rqakqu5q.Default (release)/chrome/JS/sine.uc.mjs'.`

This file isnt there I only have test.uc.js, 2 userChrome js files and an engine folder.

I hope this can help. Ty for the great work in general

EDIT: Tried to install it with v2.1.1, the file is present now but the issue persists

**Comment by mlelien** [comment]
Thank you, I cleared the JS folder and reinstalled with the most up-to-date installer but Sine's still not showing up.

<img width="2140" height="1230" alt="Image" src="https://github.com/user-attachments/assets/10716506-adb2-41a8-92a0-8af86bb1eff5" />

**Comment by thegoldknight** [comment]
> [@thegoldknight](https://github.com/thegoldknight) There has been an update. Could you try deleting the JS folder from your chrome folder and then reinstalling via the auto-installer now?

deleted JS folder and reinstalled with no luck. 

<img width="1440" height="249" alt="Image" src="https://github.com/user-attachments/assets/3ae44b4a-d91b-4189-9529-3e83b73b34b0" />

**Comment by CosmoCreeper** [comment]
@mlelien Ensure that the path to your JS folder in your chrome folder has permissions set to read & write for your user, not just the system, otherwise it can't remove, edit, or create stuff in that directory. Also, what mods do you have? Preferences are messed up.

**Comment by CosmoCreeper** [comment]
@Exclesa Reinstall now. There was an issue I thought I fixed yesterday I believe, after you posted.

**Comment by CosmoCreeper** [comment]
@LimoSenpai Okay, so, is there no sine.uc.mjs file in your JS folder?

**Comment by iza001** [comment]
Same issue here
Zen Browser beta 1.14.3b (Firefox 140.0.4) (64-bit)

<img width="1224" height="833" alt="Image" src="https://github.com/user-attachments/assets/dc8ae49e-0aff-446a-91a3-5e1372f4cadd" />

**Comment by CosmoCreeper** [comment]
@iza001 Yeah, same permissions issue as I have stated above.

> Ensure that the path to your JS folder in your chrome folder has permissions set to read & write for your user, not just the system, otherwise it can't remove, edit, or create stuff in that directory. Also, what mods do you have? Preferences are messed up.

**Comment by LimoSenpai** [comment]
yeah idk maybe its is a diffrent issue but I noticed it together with the marketplace not being there when I reinstalled Zen the other day

<img width="846" height="320" alt="Image" src="https://github.com/user-attachments/assets/9f3b15f7-8e10-40a1-ace2-8c0b0bbabc1e" />

**Comment by dante64ster** [comment]
Hi! That was my mistake too. Now I have managed to get the authorization, I have the sine, but nothing in the marketplace.

<img width="1302" height="621" alt="Image" src="https://github.com/user-attachments/assets/9d83e886-2fdc-49b9-b646-f1787f5467db" />

**Comment by CosmoCreeper** [comment]
@dante64ster Uncheck the custom marketplace in the Sine settings.

@LimoSenpai Looks like you're missing sine.uc.mjs. Extract that zip and overwrite the files in that location, then delete the zip.

**Comment by dante64ster** [comment]
> [@dante64ster](https://github.com/dante64ster) Uncheck the custom marketplace in the Sine settings.
> 
> [@LimoSenpai](https://github.com/LimoSenpai) Looks like you're missing sine.uc.mjs. Extract that zip and overwrite the files in that location, then delete the zip.

Thank you very much for your quick help, so I could fix my mistake and it works perfectly.

**Comment by mlelien** [comment]
> [@mlelien](https://github.com/mlelien) Ensure that the path to your JS folder in your chrome folder has permissions set to read & write for your user, not just the system, otherwise it can't remove, edit, or create stuff in that directory. Also, what mods do you have? Preferences are messed up.

I just changed the JS folder permissions and didn't manually delete the folder but let the installer remove Sine. There's an error in uninstalling but no errors when viewing the settings page. Sine marketplace still isn't there though.

<img width="1950" height="542" alt="Image" src="https://github.com/user-attachments/assets/6e2560e1-489b-4393-8426-14fe44d77b2a" />

<img width="2508" height="1774" alt="Image" src="https://github.com/user-attachments/assets/4f9af0e4-10e9-4aca-9e74-ed89816a2421" />

**Comment by TheBlueHarvest** [comment]
the marketplace doesn't show up here also, here's the log:

<img width="1920" height="1028" alt="Image" src="https://github.com/user-attachments/assets/e84e67ba-ac9b-4cb5-a6ab-32355cb4748d" />

**Comment by Campus00** [comment]
Hey, I also have the problem where I have Sine installed, the mods I have work, but the marketplace shows no mods. I have downgraded from 1.14.4b to 1.14b, where it worked.

<img width="771" height="883" alt="Image" src="https://github.com/user-attachments/assets/bcebe305-328a-41a8-9d7b-c78eb6593945" />

**Comment by CosmoCreeper** [comment]
@Campus00 Okay, I see you on Discord. It'll be easier to talk through that.

@TheBlueHarvest Did you try removing the JS folder manually and reinstalling via the auto-installer?

@mlelien You need to remove it manually cause the JS folder contains certain contents that the uninstaller will not remove.

**Comment by CosmoCreeper** [comment]
@thegoldknight I'm so, so, so sorry for not responding. I just couldn't figure it out. It looks like your issue is with Sine not loading on the settings page, and I finally found something!

Set this pref, ```userChromeJS.persistent_domcontent_callback``` in ```about:config``` to true, if it isn't already, then restart your browser and see if it pops up.

**Comment by TheBlueHarvest** [comment]
> [@Campus00](https://github.com/Campus00) Okay, I see you on Discord. It'll be easier to talk through that.
> 
> [@TheBlueHarvest](https://github.com/TheBlueHarvest) Did you try removing the JS folder manually and reinstalling via the auto-installer?
> 
> [@mlelien](https://github.com/mlelien) You need to remove it manually cause the JS folder contains certain contents that the uninstaller will not remove.

@CosmoCreeper Thank you very much, just did that and it solved the issue!

**Comment by mlelien** [comment]
@CosmoCreeper I changed the JS folder in Chrome permissions to read & write for admin and manually deleted the folder. The install was successful but I'm getting console errors.

<img width="460" height="160" alt="Image" src="https://github.com/user-attachments/assets/f1346666-374b-48b1-8287-ea6ae0436716" />

<img width="2150" height="1352" alt="Image" src="https://github.com/user-attachments/assets/0d1a336e-2149-4201-a037-30b75f20f4e2" />

**Comment by CosmoCreeper** [comment]
@mlelien JS folder needs to have read & write permissions for all users. Also, looks like one of your mods is corrupt.

**Comment by thegoldknight** [comment]
Hey @CosmoCreeper, all good, I been online much due to travel, and when I have been online working without sine hasn't been a problem. 

> Set this pref, `userChromeJS.persistent_domcontent_callback` in `about:config` to true, if it isn't already, then restart your browser and see if it pops up.

Sorry to say though, I tried this but with no luck. Should I try reinstalling Sine with a clean installation of Zen?


UPDATE: I installed Sine on a new profile of Zen, and the Sine page appears on the settings page. 
Left: original profile (problematic) Right: new profile

<img width="1440" height="875" alt="Image" src="https://github.com/user-attachments/assets/84a65b45-ca1b-4885-8b4a-109154a46f6f" />

**Comment by CosmoCreeper** [comment]
@thegoldknight Okay, yeah, looks like something's up with your profile. Idk what though. Did the persistent dom callback return to false again on your old profile?

**Comment by thegoldknight** [comment]
@CosmoCreeper Nope. It was always true even when I checked to change it.

**Comment by CosmoCreeper** [comment]
@thegoldknight yeah...i'm sorry, i just don't have any idea what it could be. maybe there is a pref I'm missing that is on by default, but off on yours?

**Comment by sinazadeh** [comment]
Marketplace was disappeared and I couldn't remove a mod (advanced tab groups) so I reinstalled the Sine and now some mods stopped working :)) I already cleared startup cache. Any solutions?

**Comment by sinazadeh** [comment]
Marketplace was disappeared and I couldn't remove some mods

> Marketplace was disappeared and I couldn't remove a mod (advanced tab groups) so I reinstalled the Sine and now some mods stopped working :)) I already cleared startup cache. Any solutions?

Reinstalling all mods resolved the issue.

**Comment by mlelien** [comment]
> [@mlelien](https://github.com/mlelien) JS folder needs to have read & write permissions for all users. Also, looks like one of your mods is corrupt.

Thank you, I changed the read and write permissions to everyone, deleted the folder, then reinstalled. It doesn't look like I have any Zen mods installed based on this screenshot but if I do, I can't find where to remove it.

I changed the read & write permissions with this command:

```
sudo find "/Users/emilylien/Library/Application Support/zen/Profiles/2gy2sejq.Default (release)-1/chrome/JS" -type d -exec chmod 777 {} +
sudo find "/Users/emilylien/Library/Application Support/zen/Profiles/2gy2sejq.Default (release)-1/chrome/JS" -type f -exec chmod 666 {} +
```

<img width="512" height="206" alt="Image" src="https://github.com/user-attachments/assets/251f0e61-3378-4430-bcfc-bafe4ca85978" />

<img width="2496" height="1648" alt="Image" src="https://github.com/user-attachments/assets/6d816305-be0b-4e26-8284-849b668128d4" />

<img width="2114" height="1780" alt="Image" src="https://github.com/user-attachments/assets/943dabc0-4702-43f5-9737-ef1a28889b48" />

**Comment by CosmoCreeper** [comment]
@mlelien do the same thing to the engine folder.

**Comment by lr00rl** [comment]
same issue, i use the latest binay `sine-linux-x64`, installed successfully. And i also "Clear Startup Cache" many times, it still no  "Cosine Mods" in setting page. I make some simple debug hope to be helpful:

Add a console.log in `JS/sine.uc.mjs` file:

<img width="1017" height="687" alt="Image" src="https://github.com/user-attachments/assets/4bb69543-d3f5-4cd3-a966-6d96d98ea523" />

and below is the only error when i just start zen and go into setting page:

<img width="1296" height="1075" alt="Image" src="https://github.com/user-attachments/assets/29b65438-693b-4482-ac6c-445f017d8b38" />

And, i can not find `fx-autoconfig` or something related in `about:support` page.

**Comment by CosmoCreeper** [comment]
@lr00rl How long ago did you install Sine?

**Comment by MrOtherGuy** [comment]
Hi the `UC_API.SharedStorage.widgetCallbacks` error is likely caused by fx-autoconfig version `0.10.6` which does not expose the widgetCallbacks map anymore. It was never really part of SharedStorage, I just had it stuffed there because it was actually necessary to have it available *somewhere* for our customizable widget code to work. But ever since I removed inline event listeners (which was quite some time ago) the widgetCallbacks map didn't need to stay exposed to window scope. 

I'm not sure what it is used for here, but I would suggest just defining some other place to store custom state, because widgetCallbacks was always an internal thing used by fx-autoconfig, not something to be used by other scripts.

Something like this perhaps:

```js
// initialization

UC_API.SharedStorage.SineFetches = {};
// ...
// when fetching 
let SineFetches = UC_API.SharedStorage.get("SineFetches");
SineFetches[fetchId] = fetchResults
```

Note, you can *currently* also access `UC_API.SharedStorage.get("SineFetches")` like this: `UC_API.SharedStorage.SineFetches` but I'm not sure how long I'm going to support that form. I don't have any plans to remove it in near future, and the only thing why I would like to do so is because it's feels kinda odd to have two different ways to access the same thing. However, if compatibility with old fx-autoconfig is an issue, then you could just write your code always using the `UC_API.SharedStorage.SineFetches` form because it should work with fx-autoconfig `0.10.6` and earlier:

```js
// initialization
UC_API.SharedStorage.SineFetches = {};

// read/write
let SineFetches = UC_API.SharedStorage.SineFetches;
SineFetches[fetchId] = fetchResults;
```

**Comment by lr00rl** [comment]
> [@lr00rl](https://github.com/lr00rl) How long ago did you install Sine?

about 3 or 4 hours ago. Today is my first time to install zen and sine

**Comment by CosmoCreeper** [comment]
@lr00rl Yeah, I just silently updated the auto-installer to install the older version of fx-autoconfig temporarily. If you reinstall now, it should work.

@MrOtherGuy Yeah, the main issue is that working around the updating is a bit complex, but I'll update Sine so that it uses the new version unless the user is on the old version (also, I will make it so new updates to Sine will update fx-autoconfig along with itself.)

EDIT: @MrOtherGuy I do have a problem where it takes two clicks on a notification for the click event of the button to actually be triggered. Do you know anything about that?

**Comment by MrOtherGuy** [comment]
> I do have a problem where it takes two clicks on a notification for the click event of the button to actually be triggered. Do you know anything about that?

No clue. What kind of notification are you clicking, and what is it supposed to do? Is that a new issue? I could maybe see how update to fx-autoconfig `0.10.2` could have caused something of sorts, but that was way back in January.

**Comment by CosmoCreeper** [comment]
@MrOtherGuy I have a notification that pops up using ```UC_API.Notifications.show``` and I do so from the settings page (although the same issue occurs when I do it in the main browser window.) I pass it a label, priority, and a buttons array that contains a singular button that allows the user to restart the browser.

```js
showToast(label="Unknown", priority="warning", restart=true) {
    const ifToastExists = Array.from(this.globalDoc.querySelectorAll("notification-message"))
        .some(notification => notification.__message === label);
        
    if (!ifToastExists) {
        const buttons = restart ? [{
          label: "Restart",
          callback: () => {
              ucAPI.restart(true);
              return true;
          }
        }] : [];

        UC_API.Notifications.show({
            priority,
            label,
            buttons,
        });
    }
},
```

**Comment by CosmoCreeper** [comment]
For those wondering what unresolved issues still remain here, well, here they are:
- [ ] thegoldknight: Issue with a profile, likely not Sine's fault directly, but still unresolved.
- [ ] @mlelien: Known permissions issue and there is a solution.

**Comment by GalaxyXYZ888** [comment]
<img width="3839" height="1624" alt="Image" src="https://github.com/user-attachments/assets/a4fe15b8-8102-46b9-81aa-7923319347e8" />


I am having a similar problem. Sine doesn't appear and zen mods are blocked (nothing in it and non responsive) i cant uninstall sine and if i reinstall nothing changes. I also tried to delete the JS folder inside the chrome folder inside the default profile, but i also have sine stuff inside the default (release) idk if this is intended or not. 

Also i am kinda confused about the release and default folders in general...

If you need more info pls tell me.

For context this happened like 1 or 2 weeks ago in a zen update.

**Comment by MrOtherGuy** [comment]
> [@MrOtherGuy](https://github.com/MrOtherGuy) I have a notification that pops up using `UC_API.Notifications.show` and I do so from the settings page (although the same issue occurs when I do it in the main browser window.) I pass it a label, priority, and a buttons array that contains a singular button that allows the user to restart the browser.
> 
> showToast(label="Unknown", priority="warning", restart=true) {
>     const ifToastExists = Array.from(this.globalDoc.querySelectorAll("notification-message"))
>         .some(notification => notification.__message === label);
>         
>     if (!ifToastExists) {
>         const buttons = restart ? [{
>           label: "Restart",
>           callback: () => {
>               ucAPI.restart(true);
>               return true;
>           }
>         }] : [];
> 
>         UC_API.Notifications.show({
>             priority,
>             label,
>             buttons,
>         });
>     }
> },

I tried this with minimal changes that allow it to function without any additional code and it seems to work correctly - the button action is triggered on first click.

However, if I run the code such that the notification is shown on startup, but the Firefox window *is not focused*, then in that circumstance the button does not function on first click. That is to be expected though, because if `window` is not given in the `Notifications.show()` call then fx-autoconfig tries to use last focused browser window - but if the initial window was never focused then fallback doesn't exist either. But since you clicked it, the window becomes last focused window after the first click event is handled. At least, I think that's what might be going on.

**Comment by CosmoCreeper** [comment]
@MrOtherGuy Well, on my end, there is only one window open. I even tried specifying the window, but still nothing. Although, what do you mean by on startup? Like right after the browser launches?

EDIT: I also tested using ```await UC_API.Runtime.startupFinished()```, still doesn't work.

EDIT2: Also, tried your solution for SharedStorage and it works on the old version, just gotta test on the new one now.

**Comment by CosmoCreeper** [comment]
@GalaxyXYZ888 Reinstall via the auto-installer. This issue was fixed a bit ago, but people affected by it could not update.

**Comment by Qwak-btw** [comment]
i am having the same issue ive completely  reinstalled zen then used auto installer and it doesn't show

**Comment by MrOtherGuy** [comment]
On second look, I don't think startup has anything to do with this. I researched this a bit, and found out that there is a security feature built into the notification box that disables that prevents the button action to be taken if it's clicked too soon after the notification is created or too soon  after the window becomes focused. This change is rather new, it was implemented in Firefox 136 but was uplifted to ESR 128.8 as well. I suppose I should note here that I'm just testing this stuff in Firefox Nightly with plain fx-autoconfig - I don't have Zen nor Sine installed.

I'll add an option to `UC_API.Notification.show()` that can be used to disable the clickjacking protection feature, which should then resolve the button being unclickable at first issue.

**Comment by MrOtherGuy** [comment]
With fx-autoconfig version `0.10.7` you'll want to supply additional `disableClickJackingProtection` property when creating the notification.

```js
UC_API.Notifications.show({
    priority,
    label,
    buttons,
    disableClickJackingProtection : true
});
```

**Comment by neoapps-dev** [comment]
i had this issue too, i had to delete my `chrome` directory and reinstall sine

**Comment by CosmoCreeper** [comment]
@neoapps-dev oh, prob the old auto-installer with fx-autoconfig. Shouldn't happen again.

**Comment by XIVIX134** [comment]
I can't seem to get it to work

the marketplace button disappeared i reinstalled and now the mods also disappeared 


I have twilight with Cosine

**Comment by CosmoCreeper** [comment]
@XIVIX134 Press ctrl+shift+j. any errors?

**Comment by XIVIX134** [comment]
@CosmoCreeper 

<img width="1050" height="1657" alt="Image" src="https://github.com/user-attachments/assets/fbec6755-83eb-4c5e-b429-b91a74be57ca" />

**Comment by EcoJvr101** [comment]
Sine Marketplace disappeared. I've read about the issue a bit, but I still don't know how to fix it. 

<img width="1292" height="761" alt="Image" src="https://github.com/user-attachments/assets/f8cfb3c4-39a0-41c5-9316-550c43db4752" />

<img width="1599" height="845" alt="Image" src="https://github.com/user-attachments/assets/3997f6fb-8b44-4ed9-9e25-56891e744d8a" />

**Comment by CosmoCreeper** [comment]
@XIVIX134 did you clear startup cache and restart again?

@EcoJvr101 Re-get the auto-installer from this repo and reinstall. https://github.com/CosmoCreeper/Sine/releases/latest

I silently updated the auto-installer a while ago to fix your issue.

**Comment by XIVIX134** [comment]
@CosmoCreeper How do i do that?

**Comment by EcoJvr101** [comment]
@CosmoCreeper It worked, Thanks man great work jaja

**Comment by alangm-98** [comment]
@CosmoCreeper The marketplace doesn't even appear on mine. I'm using Linux (Arch, btw). I had trouble during installation with permissions and had to use sudo for the installation commands.

**Comment by CosmoCreeper** [comment]
@alangm-98 press ctrl+shift+j, what errors?

@XIVIX134 go to ```about:support``` and click clear startup cache at the top-right-ish.

**Comment by XIVIX134** [comment]
@CosmoCreeper Nope this didn't fix it


Edit: Reinstalling after doing that seemed to have fixed it Thanks for the help

**Comment by CosmoCreeper** [comment]
@XIVIX134 what do the logs say now? Sine is likely loading now, just having a different error.

**Comment by XIVIX134** [comment]
@CosmoCreeper 

<img width="701" height="694" alt="Image" src="https://github.com/user-attachments/assets/706dd471-9685-499e-9b6c-1f064d7419f3" />

I am just having this new issue

**Comment by CosmoCreeper** [comment]
@XIVIX134 turn off custom marketplace.

**Comment by XIVIX134** [comment]
@CosmoCreeper Now there is like 3 mods

**Comment by alangm-98** [comment]
@CosmoCreeper  This are the errors

<img width="946" height="969" alt="Image" src="https://github.com/user-attachments/assets/2633a74d-b25c-44c4-b840-d9994ca61e11" />

**Comment by CosmoCreeper** [comment]
@alangm-98 change the permissions to your JS folder in your chrome folder to allow all users read & write permissions. Do the same to the engine folder inside of the JS folder.

**Comment by alangm-98** [comment]
@CosmoCreeper Thanks, it worked!

**Comment by sws1213** [comment]
I cleared startup cache, restarted and tried reinstalling but marketplace is still not showing. The console is showing the same error.

<img width="1116" height="276" alt="Image" src="https://github.com/user-attachments/assets/e715fb79-53b7-44a8-a6ab-a83e1275f696" />

**Comment by CosmoCreeper** [comment]
@sws1213 get the auto-installer from here again, do no5 use the one you have locally. I silently changed the installer to fix a issue with autoconfig.

**Comment by Glax3210** [comment]
I'm not sure, but this link doesn't seem to do anything. I’m not even sure if the JSON file is available: https://cosmocreeper.github.io/Sine/data/marketplace.json

<img width="686" height="686" alt="Image" src="https://github.com/user-attachments/assets/7fcdb858-6f1d-4f68-ac22-66c0862221fd" />

**Comment by CosmoCreeper** [comment]
@Glax3210 disable external marketplace in Sine settings.

**Comment by SlyCedix** [comment]
> I cleared startup cache, restarted and tried reinstalling but marketplace is still not showing. The console is showing the same error.
> <img alt="Image" width="1116" height="276" src="https://private-user-images.githubusercontent.com/139040593/468454708-e715fb79-53b7-44a8-a6ab-a83e1275f696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM0NDg1OTksIm5iZiI6MTc1MzQ0ODI5OSwicGF0aCI6Ii8xMzkwNDA1OTMvNDY4NDU0NzA4LWU3MTVmYjc5LTUzYjctNDRhOC1hNmFiLWE4M2UxMjc1ZjY5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyNVQxMjU4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTRmYmNlZDVkNTRkMzhiYzMzMmZkYTEwNWM1M2JmY2UwMjRhZTEwZTBmNDY2YTVhMTIzYWI5MDRmNzdlZDY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VlpRE6EoA1JwyiW24YhtL4j06oKOnw0IB2KhyC9eSmY">

Having the same issue.

Windows 11, manual install on a user installation of zen. Can't run the installer as I don't have admin.

**Comment by CosmoCreeper** [comment]
@SlyCedix you need admin permissions to edit the zen program files, needed for Sine.

**Comment by SlyCedix** [comment]
> [@SlyCedix](https://github.com/SlyCedix) you need admin permissions to edit the zen program files, needed for Sine.

Why? The zen program files are installed to `%LOCALAPPDATA%/Zen Browser` with no admin perms

**Comment by CosmoCreeper** [comment]
@SlyCedix oh. Okay. I guess we'll go over what you did to manually install then.

First, press ctrl+shift+j in zen. This will open a logging console where I can see if fx-autoconfig is loading.

**Comment by KingOreoTheThird** [comment]
Uhh idk if this is just me but I cant find Nebula in the marketplace. Also when enabling external it gives me undefined

**Comment by CosmoCreeper** [comment]
@KingOreoTheThird go to about:config and add zen.browser.is-cool as a boolean, set it to whatever you want.

For the undefined, enable external marketplace, set the input field to empty, and disable it again.

**Comment by SlyCedix** [comment]
<img width="926" height="150" alt="Image" src="https://github.com/user-attachments/assets/5332e19c-f89c-4c45-992f-798f368db662" />

Install steps taken:
* [config.js](https://github.com/MrOtherGuy/fx-autoconfig/blob/master/program/config.js) added to `%LOCALAPPDATA%/Zen Browser`
* [config-prefs.js](https://github.com/MrOtherGuy/fx-autoconfig/blob/master/program/defaults/pref/config-prefs.js) added to `%LOCALAPPDATA%/Zen Browser/defaults/pref`
* [fx-autoconfig chrome](https://github.com/MrOtherGuy/fx-autoconfig/tree/master/profile/chrome) added to `%APPDATA%/zen/Profiles/ynhie7ww.Default (release)/chrome`
* [Sine engine.zip](https://github.com/CosmoCreeper//Sine/tree/main/deployment/engine.zip) extracted to `%APPDATA%/zen/Profiles/ynhie7ww.Default (release)/chrome/JS`
* `Clear Startup Cache` clicked in about:support
* Zen restarted when prompted in toast after clear cache restart

**Comment by CosmoCreeper** [comment]
@SlyCedix reinstall auto-installer from this repo and install again. There was an issue i silently fixed in this auto-installer.

**Comment by gradylink** [comment]
I'm also having the issue of not being able to install Sine. For context, I'm on Arch. I managed to get Sine installed a few months ago, but it wouldn't let me install anything. Then it disappeared and when I try to reinstall nothing happens. The console on the settings page is just this:

<img width="985" height="349" alt="Image" src="https://github.com/user-attachments/assets/6530b960-419f-419e-b448-2e65138339f1" />

EDIT: I haven't changed profiles or anything since Zen was in alpha, so I wonder if that could be messing it up somehow.

**Comment by SlyCedix** [comment]
> [@SlyCedix](https://github.com/SlyCedix) reinstall auto-installer from this repo and install again. There was an issue i silently fixed in this auto-installer.

I cannot. The installer requires admin even when zen is installed in a user location

**Comment by CosmoCreeper** [comment]
@SlyCedix Oh, install fx-autoconfig repo from this url.
https://github.com/MrOtherGuy/fx-autoconfig/tree/f1f61958491c18e690bed8e04e89dd3a8e4a6c4d

**Comment by TUGMindboggle** [comment]
Also having this issue. I've attempted pretty much everything in the thread and no luck. Any ideas?

<img width="898" height="546" alt="Image" src="https://github.com/user-attachments/assets/81147f71-b395-4bd6-ba42-dda6fd12f999" />

**Comment by CosmoCreeper** [comment]
@TUGMindboggle 
Go to your profile folder > chrome folder, and run this command:
```sudo chown {user}:{user} ./JS && sudo chown {user}:{user} ./JS/engine```
Replace {user} with your username.

**Comment by TUGMindboggle** [comment]
"'sudo' is not recognized as an internal or external command, operable program or batch file."

I'm running Windows, btw. in case you thought i was on Linux?

**Comment by CosmoCreeper** [comment]
@TUGMindboggle oh, didn't know. Do you have discord? This is a known issue I'm trying to fix and I have 5 other ppl with the same issue. If you have discord you can join the Sine server and I can ping u when I figure it out.

**Comment by CosmoCreeper** [comment]
@TUGMindboggle oh, didn't know. Do you have discord? This is a known issue I'm trying to fix and I have 5 other ppl with the same issue. If you have discord you can join the Sine server and I can ping u when I figure it out.

**Comment by dante64ster** [comment]
Hi
Yesterday, it wanted to update in the browser and after rebooting the Sine market disappeared.

**Comment by CosmoCreeper** [comment]
@dante64ster press ctrl+shift+j and see if there are any errors.

**Comment by gradylink** [comment]
I asked earlier didn't get a response, just realized my logs image didn't upload, here it is:

<img width="1292" height="741" alt="Image" src="https://github.com/user-attachments/assets/cfd52ea6-1e1f-4dbc-9663-29c5f5745a5a" />

EDIT: maybe I need to just `chown` those files?

**Comment by CosmoCreeper** [comment]
@gradylink okay, i apologize for the lack of response. this issue has been getting quite crowded as the title is quite generic, so i will be closing it and requesting that all people with remaining issues make new issues.

As for your issue directly, yes, you would just need to ```sudo chown``` those files.

Go to your profile folder > chrome folder > then ```sudo chown``` the ```./JS``` folder, just make sure to run it with the parameter ```-R``` to ensure that all subfolders and files get this change applied as well.

**Comment by gradylink** [comment]
> [@gradylink](https://github.com/gradylink) okay, i apologize for the lack of response. this issue has been getting quite crowded as the title is quite generic, so i will be closing it and requesting that all people with remaining issues make new issues.
> 
> As for your issue directly, yes, you would just need to `sudo chown` those files.
> 
> Go to your profile folder > chrome folder > then `sudo chown` the `./JS` folder, just make sure to run it with the parameter `-R` to ensure that all subfolders and files get this change applied as well.

@CosmoCreeper 

still not working, I got a pop up for a Sine update told me to restart, I pressed the button to restart. After Zen restarted, I have these errors:

<img width="1722" height="1403" alt="Image" src="https://github.com/user-attachments/assets/8812e781-e39a-4c1a-b214-8b1be2a32ae0" />

<img width="1740" height="1236" alt="Image" src="https://github.com/user-attachments/assets/341a64f7-30c1-41ae-85ff-55bb29504482" />

EDIT: this was all **after** clearing the startup cache.

**Comment by CosmoCreeper** [comment]
@gradylink go to https://github.com/CosmoCreeper/Sine/main/deployment/engine.zip, download it, and extract it into your JS folder. that should be it.

**Comment by CosmoCreeper** [comment]
@gradylink I'm closing this issue and locking it to keep stuff clean. Please create a new issue if you have another problem.
